server:
  port: 8090

spring:
  redis:
    database: 0
    timeout: 3000
    sentinel:
      master: mymaster
      nodes: 120.78.219.38:26379,120.78.219.38:26380,120.78.219.38:26381
      lettuce:
        pool:
          max-idle: 50
          min-idle: 10
          max-active: 100
          max-wait: 1000